Se creo nuevo Item
GameNova-Studio/path-to-the-throne pull request #133
Opened 2024-10-31 07:01 UTC by YsaLuna

Se agrego nuevo Item llamado Papiro
Se creo nueva Carpeta "Ysamar" para prueba del item

2024-10-31 12:02 UTC, manuq commented
@YsaLuna ahora entiendo a qué se referían con crear una carpeta para cada integrante del equipo. Es cierto que así se van a evitar conflictos, pero no es la idea. Porque si cada uno tiene una escena player.tscn distinto, ¿en qué momento se unen los distintos cambios? La idea es que todos editen la misma escena player.tscn en ramas, y que las ramas se unan a main lo antes posible.

2024-10-31 17:07 UTC, manuq requested changes
El mensaje del commit es muy genérico: "Se creo nuevo item". Debería al menos mencionar qué item se está agregando.

Hay un cambio que no se explica relacionado con una nueva escena player.tscn. Y dos escenas agregadas a una nueva carpeta.

2024-10-31 17:07 UTC, manuq commented on godot/entities/items/item.tscn
> +scale = Vector2(0.338542, 0.291667)
Este cambio en la posición y escala del nodo Sprite2D, ¿no altera los items preexistentes?

2024-10-31 17:07 UTC, manuq commented on godot/Ysamar/item.tscn
> +[gd_scene load_steps=4 format=3 uid="uid://c2nf37t23mq0p"]
¿Porqué esta escena está en una carpeta Ysamar?

2024-10-31 21:02 UTC, dsd commented
Este Pull Request es relacionado a uno de los tareas (Issues/Backlog)? Si es asi, tambien puedes incluir un enlace a ese issue en el mensaje del commit.

2024-11-01 13:59 UTC, manuq approved these changes
En cuanto a código está perfecto, así que vamos a unir con main. Vimos con @YsaLuna que el asset va a necesitar edición. Lo dejamos para alguien con el rol de arte.

2024-11-01 13:59 UTC, merged

2024-11-01 14:06 UTC, manuq commented
> Este Pull Request es relacionado a uno de los tareas (Issues/Backlog)? Si es asi, tambien puedes incluir un enlace a ese issue en el mensaje del commit.

@YsaLuna ¡nos faltó atender a este comentario! La próxima vez, mencionemos el número de tarea en el mensaje del commit. Por ejemplo:
```
Se creo nuevo Item Papiro

Se agrega una imagen papiro y se cambia la escena item para usar el
papiro en el juego.

#115
```