Completadas tareas 107 y 111, correspondientes a sonidos.
GameNova-Studio/path-to-the-throne pull request #146
Opened 2024-11-07 23:25 UTC by Chox13

Se realizó las tareas:
107: Sonidos de entrada y salida de nivel.
111: Sonidos de ataque y curación en combate.

Los sonidos han sido debidamente añadidos en attributions.txt con sus debidos enlaces de origen, así como su licencia de Creative Commons 0.

2024-11-08 13:51 UTC, manuq reviewed
Excelente @Chox13! Veo que has podido con los conflictos. Sólo un detalle de mi parte:

Los mensajes de commit están muy bien, excepto por la primera línea. Debería decir resumidamente lo que el commit hace. La referencia a la tarea está bien, pero debería ir en el cuerpo del mensaje. Entonces el primer mensaje de commit quedaría:

> Emite sonidos al cambiar el nivel
>
> 
> Se han añadido los sonidos de cambio de nivel:
> - Personaje moviendo su espada.
> - Cueva destruyéndose.
> 
> Los sonidos añadidos fueron verificados como Creative Commons y se encuentran detallados en attributions.txt con su respectivo enlace.
>
> https://github.com/GameNova-Studio/path-to-the-throne/issues/111

2024-11-08 14:23 UTC, YsaLuna commented
Me parece bien pudiste solucionar los conflictos y empezar de nuevo, pero con lo que ya tenias @Chox13 solo un pequeño detalle poner una mejor descripción para el commit y tratar que sea uno solo.

2024-11-08 14:58 UTC, manuq commented
> Me parece bien pudiste solucionar los conflictos y empezar de nuevo, pero con lo que ya tenias @Chox13 solo un pequeño detalle poner una mejor descripción para el commit y tratar que sea uno solo.

De mi parte, sólo cambiaría los mensajes como puse arriba. En cuanto a que sea un solo commit, creo que está bien así, siendo dos. Es más, yo dividiría el segundo commit. Pero a modo de seguir avanzando y unir esto lo antes posible, dejémoslo en 2 commits. ¿Les parece?

2024-11-08 15:09 UTC, dsd commented on godot/scenes/levels/story_mode/level_1/level_1.tscn
> +[node name="golpe" type="AudioStreamPlayer2D" parent="Player"]
Pregunta para @manuq (el experto de Godot):
En este commit, se duplica los AudioStreamPlayer en 3 niveles, pero el codigo de reproducir sonidos se ubica dentro de Door/Player. Seria posible/factible/mejor poner los AudioStreamPlayer directamente en Door/Player y no duplicarlos para cada nivel?

2024-11-08 15:43 UTC, manuq commented on godot/scenes/levels/story_mode/level_1/level_1.tscn
> +[node name="golpe" type="AudioStreamPlayer2D" parent="Player"]
Buen punto @dsd . Eso estaba por comentarles. Veo que están haciendo los cambios en cada nivel. ¿Es lo que quieren? Consideren que de esta forma, cada vez que se agregue un nivel tendrán que hacer este trabajo nuevamente. La ventaja es que permite personalizar los niveles. ¿Pero a qué costo?

Lo mismo vale para los sonidos agregados a los NPCs en este mismo pull-request (archer, goblin, etc). Si todos los NPCs van a tener un sonido de ataque, quizá convenga usar alguna de las abstracciones que hay en el proyecto (NPC, fighter, fighter_with_reward, etc). O usar composición, crear una escena "GoblinAttackSound" que sea el AudioStreamPlayer2D duplicado en todos los goblins (por ejemplo).

2024-11-08 18:06 UTC, dsd commented on godot/scenes/levels/story_mode/level_1/level_1.tscn
> +[node name="golpe" type="AudioStreamPlayer2D" parent="Player"]
Seria facil de mover el AudioStreamPlayer a las escenas de Door/Item en este commit, o esa idea reqiere un refactor de la estructura del  juego?

2024-11-12 23:00 UTC, dsd commented
@Chox13 Alguna noticia, vas a cambiar los mensajes?
Aqui una demo: https://www.youtube.com/watch?v=zep60XM2_eI

2024-11-13 06:13 UTC, Chox13 commented
> @Chox13 Alguna noticia, vas a cambiar los mensajes? Aqui una demo: https://www.youtube.com/watch?v=zep60XM2_eI

Hola, he realizado los cambios de los mensajes para la correspondiente aprobación del pull request. ¡Muchas gracias!

2024-11-13 10:33 UTC, manuq commented
> > @Chox13 Alguna noticia, vas a cambiar los mensajes? Aqui una demo: https://www.youtube.com/watch?v=zep60XM2_eI
> 
> Hola, he realizado los cambios de los mensajes para la correspondiente aprobación del pull request. ¡Muchas gracias!

@Chox13 qué raro, aunque veo que has actualizado el pull request, los mensajes de los commits no han cambiado:
![Captura desde 2024-11-13 07-31-27](https://github.com/user-attachments/assets/358218e6-2309-4c2b-84f8-9a6f2cd3ff8f)

2024-11-13 10:50 UTC, manuq requested changes
Los sonidos de "golpe" y de "entrar" se han agregado a cada nivel (level_1, level_2, level_3). Pero corresponde colocarlas en las escenas Player y Door, respectivamente.

¿Qué ocurre si creamos un nuevo nivel y nos olvidamos de agregar un nodo de nombre `golpe` como hijo del nodo Player? El script va a fallar cuando intente hacer `$golpe.play()`.

2024-11-13 10:50 UTC, manuq commented on godot/scenes/levels/story_mode/level_1/level_1.tscn
> +[node name="golpe" type="AudioStreamPlayer2D" parent="Player"]
Sí, debería moverse el sonido del golpe a la escena Player. No creo que se necesite un golpe distinto en cada nivel, ¿verdad @Chox13?

2024-11-14 00:11 UTC, closed without merging

2024-11-14 14:26 UTC, manuq commented
Entiendo que este pull request fue cerrado para dar lugar a #158 .