Agregar timer bar
GameNova-Studio/path-to-the-throne pull request #147
Opened 2024-11-11 00:13 UTC by GiovanniOR

Se creo ella escena y el script timer_bar (Ui).
res://ui/components/
Se importo assets en la carpeta UI/bar (3 en total).
res://assets/Tiny Swords/UI/Bar/
Se agregó timerBar a la escena Multiple_choice_scene.
Al acabar la progressbar (11 segundos) el enemigo ataca al personaje.

2024-11-12 11:56 UTC, manuq commented on godot/scenes/combat/minigames/multiple_choice_scene.gd
> +
Esta función no hace nada, por lo que debería borrarse antes de unir el pull request.

2024-11-14 14:21 UTC, YsaLuna commented
Este pull request no podra ser aceptado a menos que cambies tus assets, pues los que usas no estan dentro del Tiny Sword y no haces mención de donde los sacaste te reomiendo adaptar lo q tenemos dentro de UI/Buttons.

La descripción va bien , pero recuerda solo debe haber un commit.

2024-11-14 14:44 UTC, manuq commented
¡Gracias @jphm22 y @YsaLuna por la revisión!

Para ser más específicos con @GiovanniOR, entonces la propuesta parece ser:
- Diseñar la barra de progreso adaptando los botones existentes en el asset pack "Tiny Swords" (carpeta `godot/assets/Tiny\ Swords/UI/Buttons/`)
- De ese diseño obtener dos assets nuevos para la barra de progreso: "barra vacía" y "barra llena"
- Actualizar el pull request con esas dos nuevas imágenes.

¿@GiovanniOR te parece bien? ¿Podrías hacerlo o necesitas de alguien que tenga el rol de arte? Se puede hacer cualquier consulta de arte con la mentora Julieta.

2024-11-14 14:50 UTC, manuq requested changes
Va bien, pero necesita adaptar los dos assets desde el pack Tiny Swords.

2024-11-25 16:33 UTC, closed without merging

2024-11-25 17:16 UTC, manuq commented
@GiovanniOR, ¿porqué has cerrado este pull request?