Añadido NPC patrullero creado en escena con su script propio para que…
GameNova-Studio/path-to-the-throne pull request #159
Opened 2024-11-14 07:41 UTC by jphm22

… se mueva de izquierda a derecha #122

NPC llamado "Patrullero" que tiene la capacidad de moverse automáticamente en un patrón horizontal, patrullando un área definida dentro del nivel. El objetivo es mejorar la jugabilidad al añadir NPCs con comportamiento dinámico, lo que añade un mayor nivel de inmersión al juego.

Se ha agregado un nuevo script llamado npc_patrullero.gd y una escena Archer_Caminante.tscn que se encargan de gestionar el comportamiento del NPC patrullero. El NPC utiliza la clase CharacterBody2D para aprovechar el sistema de física de Godot y moverse de forma fluida.

A continuación, se detallan las características clave del código:

Constantes definidas:

1. VELOCIDAD_CORRER: Controla la velocidad a la que se desplaza el NPC (actualmente configurada en 50 píxeles por segundo).
2. DISTANCIA_LIMITE: Define la distancia máxima que el NPC recorrerá hacia la izquierda y derecha antes de cambiar de dirección (establecida en 200 píxeles).

Variables utilizadas:

1. posicion_inicial: Almacena la posición inicial del NPC al inicio de la escena.
2. limite_izquierda y limite_derecha: Determinan los límites entre los cuales el NPC se moverá.

Métodos implementados:

1. func _ready(): Inicializa la posición del NPC y los límites de patrullaje. Además, comienza la animación de correr.
2. func _physics_process(delta): Se encarga de gestionar el movimiento del NPC. El NPC cambia de dirección al alcanzar los límites definidos y ajusta el sprite (flip_h) para que mire en la dirección correcta

2024-11-14 15:03 UTC, manuq requested changes
No parece hacer lo que pide la tarea.

2024-11-14 15:03 UTC, manuq commented on godot/entities/characters/npcs/archer/npc_patrullero.gd
> +extends CharacterBody2D
¿Porqué este NPC hereda de CharacterBody2D y no de NPC?

La tarea #122 dice, entre otras cosas:
> (...) que si te ven combatan con vos

Y:
> (...) debería dejar de estar activo una vez les ganas.

Por lo tanto suena más a que hay que reutilizar `godot/entities/prefabs/npcs/fighter/fighter.gd` o crear un nuevo "patrol fighter".

Al heredar de CharacterBody2D y no de NPC, no va a poder interactuar con el player ni entrar en combate.

2024-11-14 16:29 UTC, jphm22 commented on godot/entities/characters/npcs/archer/npc_patrullero.gd
> +extends CharacterBody2D
Tienes razon. Ahora quiero entrar a esta rama, pero en git no me deja, espero podamos solucionarlo en la sesion

2024-11-18 22:25 UTC, manuq commented on godot/entities/characters/npcs/archer/npc_patrullero.gd
> +extends CharacterBody2D
@jphm22, ¿pudiste solucionarlo? ¿A qué te referís con que no te deja?

2024-11-26 04:55 UTC, closed without merging