Agregar animación de recibir daño al player_combat_sprite.tscn y añad…
GameNova-Studio/path-to-the-throne pull request #160
Opened 2024-11-14 09:03 UTC by jphm22

…irla a la lista de hurt_animation_names #130

Descripción del cambio:

1. Creación de nueva animación de daño: Se ha creado una nueva animación para el jugador en la que este realiza un giro en su lugar como parte de la reacción al recibir daño. Este movimiento se implementó usando un nuevo sprite que simula el efecto visual de la animación de daño.
2. Aplicación del efecto visual de daño: Para mejorar la animación, se ha agregado un efecto visual utilizando el parámetro modulate, que cambia temporalmente el color del jugador a rojo durante la animación, simbolizando el daño recibido.
3. Actualización de la lista de animaciones de daño: Se añadió la nueva animación de daño a la lista hurt_animation_names, permitiendo que el sistema de combate reconozca y ejecute esta animación cuando el jugador reciba daño.

2024-11-14 15:40 UTC, manuq commented
Este pull-request había entrado en conflicto con main por algo relativo a Godot (el número load_steps en la escena player_combat_sprite.tscn). Acabo de corregirlo. @jphm22 vas a tener que actualizar tu rama local con:
```
git fetch
git checkout Animacion_daño_player
git reset --hard origin/Animacion_daño_player
```

2024-11-14 15:53 UTC, manuq requested changes

2024-11-14 15:53 UTC, manuq commented on godot/scenes/combat/in_combat_characters/combat_sprites/player_combat_sprite.tscn
> +hurt_animation_names = Array[String](["new_animation"])
La animación está muy bien. Pero:
- Ya existe una animación "hurt" en la escena.
- Se crea una nueva animación de nombre "new_animation" en vez de editar la preexistente.

![Captura desde 2024-11-14 12-49-14](https://github.com/user-attachments/assets/f0a240f1-fdee-4299-a946-df71ae3fa8b0)


Por lo que sugiero:
- Borrar la animación "hurt"
- Luego, renombrar la animación "new_animation" a "hurt"

2024-11-14 16:26 UTC, jphm22 commented on godot/scenes/combat/in_combat_characters/combat_sprites/player_combat_sprite.tscn
> +hurt_animation_names = Array[String](["new_animation"])
Lo deje por si el usuario desea tener otra animación de daño.

2024-11-14 16:30 UTC, YsaLuna commented on godot/scenes/combat/in_combat_characters/combat_sprites/player_combat_sprite.tscn
> +hurt_animation_names = Array[String](["new_animation"])
Sugiero ponerle hurt1 , hurt2 con lo que podemos saber que tenemos diferentes animaciones de daño
les parece bien? @jphm22  @manuq

2024-11-14 16:33 UTC, jphm22 commented on godot/scenes/combat/in_combat_characters/combat_sprites/player_combat_sprite.tscn
> +hurt_animation_names = Array[String](["new_animation"])
Lo deje como new_animation porque en la asignacion pide que se cree una nueva animacion, era para señar que era la nueva animación

2024-11-14 19:49 UTC, manuq commented on godot/scenes/combat/in_combat_characters/combat_sprites/player_combat_sprite.tscn
> +hurt_animation_names = Array[String](["new_animation"])
De acuerdo con que "new_animation" no es un buen nombre para la animación. Y no creo que sea necesario dejar animaciones abandonadas dentro del proyecto. La gran ventaja de Git es que recuerda todo, todo queda en la historia. Por lo tanto si algún día nos arrepentimos y queremos volver a la animación anterior, la podemos traer de la historia de Git.

2024-11-26 04:53 UTC, YsaLuna approved these changes
Pendiente cambiar el nombre "new animation"

2024-11-27 11:21 UTC, manuq commented
¿@jphm22 necesitas ayuda con esto? Está prácticamente aprobado, es cuestión de reemplazar la animación anterior por la nueva, con el nombre que estaba antes.

2024-11-27 14:46 UTC, manuq commented
Acabo de resolver el conflicto con la rama principal. Faltaría cambiar el nombre, no a "new_animation" ni a "hurt2", sino al existente "hurt".

2024-11-28 05:16 UTC, YsaLuna approved these changes

2024-11-28 19:21 UTC, manuq commented
@jphm22 una vez más, este pull request entra en conflicto, dado que la escena player ahora tiene animaciones para "buff" y "neft" que entran en conflicto con la agregada aquí "new_animation".

2024-12-06 19:28 UTC, manuq commented
Hecho en #208 .

2024-12-06 19:28 UTC, closed without merging